Revert "Add a more descriptive message in the ValidateUpdate script."
This reverts commit dd91d1069f14ea1d189d03ee032528b4343670eb.

(cherry picked from commit 875342b445e749b990eac649c77f22225c70461e)

diff --git a/build/profiles/freenas/ValidateUpdate b/build/profiles/freenas/ValidateUpdate
--- a/build/profiles/freenas/ValidateUpdate
+++ b/build/profiles/freenas/ValidateUpdate
@@ -18,9 +18,9 @@ else
 		9.10*) sub_version=`echo ${sub_version} | cut -d '-' -f1`;
 		case $sub_version
 		in
-			(*[!0-9]*|'') echo "Cannot upgrade from ${CURRENT_VERSION} to FreeNAS 11 directly. You have to upgrade to 9.10.2 first." 1>&2 ; exit 1;;
+			(*[!0-9]*|'') echo "Cannot upgrade from ${CURRENT_VERSION} to FreeNAS 11" 1>&2 ; exit 1;;
 			(*) if [ ${sub_version} -lt 2 ]; then
-					echo "Cannot upgrade from ${CURRENT_VERSION} to FreeNAS 11 directly. You have to upgrade to 9.10.2 first." 1>&2 ; exit 1;
+					echo "Cannot upgrade from ${CURRENT_VERSION} to FreeNAS 11" 1>&2 ; exit 1;
 				fi;;
 		esac
 		;;
